# Generated by Django 5.1.6 on 2025-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Your bio here...'),
        ),
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(default='header/default.jpg', upload_to='headers/'),
        ),
    ]
