# Generated by Django 5.1.6 on 2025-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_bio_user_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_profile_icon.svg', upload_to='avatars/'),
        ),
    ]
