# Generated by Django 5.1.6 on 2025-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(help_text='ID фильма из API', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
