# Generated by Django 5.1.6 on 2025-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgb_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommovie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/movies_images', verbose_name='Изображение Категории'),
        ),
    ]
