# Generated by Django 5.1.6 on 2025-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgb_main', '0003_customgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgame',
            name='api_id',
            field=models.CharField(help_text='ID игры из API', max_length=100, unique=True),
        ),
    ]
